// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB_gtye9L63DoKRWTxZb6SRd6QKKL-ob8',
    appId: '1:390123148016:web:377af39ca179b36e962835',
    messagingSenderId: '390123148016',
    projectId: 'note-app-flutter-962a1',
    authDomain: 'note-app-flutter-962a1.firebaseapp.com',
    databaseURL: 'https://note-app-flutter-962a1-default-rtdb.firebaseio.com',
    storageBucket: 'note-app-flutter-962a1.appspot.com',
    measurementId: 'G-7HW08DFNJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7DRQLhZz44mm14kEzTblqG9mZQci7y8',
    appId: '1:390123148016:android:ea3d2ca28a4fa96c962835',
    messagingSenderId: '390123148016',
    projectId: 'note-app-flutter-962a1',
    databaseURL: 'https://note-app-flutter-962a1-default-rtdb.firebaseio.com',
    storageBucket: 'note-app-flutter-962a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGrFewPyy3mUQOXl7Ndr7UNaNzLE7YVtE',
    appId: '1:390123148016:ios:3458f01516675c02962835',
    messagingSenderId: '390123148016',
    projectId: 'note-app-flutter-962a1',
    databaseURL: 'https://note-app-flutter-962a1-default-rtdb.firebaseio.com',
    storageBucket: 'note-app-flutter-962a1.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGrFewPyy3mUQOXl7Ndr7UNaNzLE7YVtE',
    appId: '1:390123148016:ios:a1723bddda434e36962835',
    messagingSenderId: '390123148016',
    projectId: 'note-app-flutter-962a1',
    databaseURL: 'https://note-app-flutter-962a1-default-rtdb.firebaseio.com',
    storageBucket: 'note-app-flutter-962a1.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
